"""Initial migration

Revision ID: 119d11360962
Revises: 
Create Date: 2026-02-24 18:10:46.861891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119d11360962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('class_name', sa.String(length=30), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('class_name')
    )
    op.create_table('furniture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('previous_room', sa.String(length=100), nullable=True),
    sa.Column('current_room', sa.String(length=100), nullable=True),
    sa.Column('last_moved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['current_room'], ['classrooms.class_name'], name='fk_current_room'),
    sa.ForeignKeyConstraint(['previous_room'], ['classrooms.class_name'], name='fk_previous_room'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('furniture')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
