"""Update column to null true

Revision ID: 1ea1b0fdd0b0
Revises: 44c299564151
Create Date: 2026-02-26 09:42:30.515523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea1b0fdd0b0'
down_revision = '44c299564151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_furniture')
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('furniture_type', sa.String(length=100), nullable=True))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('furniture_type')

    op.create_table('_alembic_tmp_furniture',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('previous_room', sa.VARCHAR(length=100), nullable=True),
    sa.Column('current_room', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_moved', sa.DATETIME(), nullable=True),
    sa.Column('furniture_type', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['current_room'], ['classrooms.class_name'], name=op.f('fk_current_room')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
