"""Update furniture_type nullable

Revision ID: 3cd1f821f1ce
Revises: 1ea1b0fdd0b0
Create Date: 2026-02-27 14:47:15.992786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd1f821f1ce'
down_revision = '1ea1b0fdd0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.alter_column('furniture_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.alter_column('furniture_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
