"""Update furniture foreign key

Revision ID: 44c299564151
Revises: 119d11360962
Create Date: 2026-02-24 18:13:23.329694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c299564151'
down_revision = '119d11360962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_previous_room'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furniture', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_previous_room'), 'classrooms', ['previous_room'], ['class_name'])

    # ### end Alembic commands ###
